import fs from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

// Get directory path
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const dictionaryPath = path.resolve(__dirname, '../server/data/serbian-dictionary-mega.json');

// Nove srpske reči za dodati - slovo S
const additionalWords = [
  // S
  "sabah", "sabiti", "sablja", "sabljarnica", "sabljaš", "sabljaški", "sabljast", "sabor", "saborac", "sabornost", 
  "sabornik", "sabornost", "saborovati", "saborski", "sabotaža", "sabotirati", "sabrati", "sabratelja", "sabraća", "sabranost", 
  "sabran", "sabranje", "sabuha", "sabitost", "sabirač", "sabirača", "sabiranje", "sabirni", "sabirnica", "sačekati", 
  "sačekuša", "sačinitelj", "sačiniti", "sačinjen", "saćurica", "sadašnjica", "sadašnji", "sadašnjost", "sadejstvo", "sadejstvovati", 
  "sadejna", "sadilac", "sadilica", "sadionica", "saditi", "saditba", "saditi", "sadizam", "sadist", "sadistički", 
  "sadnica", "sadnice", "sadra", "sadržaj", "sadržalac", "sadržan", "sadržanost", "sadržateljka", "sadržatelj", "sadržati", 
  "sadržavati", "sadržinom", "sadržinski", "safari", "safijan", "safir", "saga", "sagibati", "saginjati", "sagitalan", 
  "sagledati", "sagledavati", "saglediv", "saglasan", "saglasnost", "saga", "sagnjiti", "sagnjilost", "sagnuti", "sagoretii", 
  "sagorevanje", "sagorevati", "sagorijevati", "sagorjeti", "sagospodar", "sagradi", "sagraditelj", "sagraditi", "saha", "sahara", 
  "saharski", "sahrana", "sahraniti", "sahranjivati", "saimara", "saja", "sajam", "sajamski", "sajdžija", "sajka", 
  "sajmište", "sajt", "sakaćenje", "sakatiti", "sakat", "sakatost", "sakato", "sakmarodna", "sakodnevno", "sakodnevica", 
  "sakoga", "sakoj", "sakoliki", "sakolik", "sakolikih", "sakom", "sakonoćno", "sakosvetski", "sakpićen", "sakralan", 
  "sakrament", "sakramentalan", "sakrati", "sakrivač", "sakrivati", "sakriverak", "sakriven", "sakrivenost", "sakrivnica", "sakristija", 
  "sakrosanktnost", "sakrosanktan", "sakroviliti", "sakta", "sakupiti", "sakupljač", "sakupljati", "sakupljanje", "sakundaran", "sakutić", 
  "salaš", "salama", "salata", "salcburški", "sale", "salep", "salepo", "salica", "salicil", "salivati", 
  "salitreni", "salitrenjača", "salitriti", "salitra", "salitrara", "salinitet", "saliv", "salivski", "salo", "salon", 
  "salonski", "salto", "salov", "salutacija", "salutirati", "salveta", "salvetice", "salvetna", "salvirati", "sam", 
  "smaritan", "samaritanski", "samica", "samljeti", "samljeven", "samljeveni", "samljevenost", "samoblok", "samobor", "samoborski", 
  "samoboštvo", "samocenjenje", "samoća", "samodefinicija", "samodeklizacija", "samodobrovoljno", "samodopadan", "samodoprinošenje", "samodostatan", "samodrštvo", 
  "samodržavlje", "samodržac", "samofabrikacija", "samofagija", "samofian", "samofokus", "samoformativno", "samoglas", "samoglasni", "samoglasno", 
  "samogradnja", "samogovor", "samogrejni", "samohatno", "samohran", "samohvala", "samoiskazivanje", "samoispitati", "samoispitivanje", "samoisticanje", 
  "samokažnjavanje", "samokleveta", "samokontrola", "samokretanje", "samokritičnost", "samokritičan", "samokreativan", "samolažno", "samoljubivo", "samoljubivost", 
  "samoljubiv", "samoljubilje", "samoljublje", "samomasakriranje", "samomedikacija", "samohodka", "samohodni", "samohod", "samom", "samomilosrdnost", 
  "samomišljenje", "samomučenje", "samomržnja", "samonametnuto", "samonametnutost", "samonikao", "samoobmana", "samoobnovljiv", "samoobnova", "samoobrazovanje", 
  "samoobrana", "samoobuzdavanje", "samoočuvanje", "samoohrabrenje", "samoodbrambeni", "samoodlučnost", "samoodbrana", "samoodgoj", "samoodlučivanje", "samoodluka", 
  "samoodrečenje", "samoodricanje", "samoodređenje", "samoodržanje", "samoodrživ", "samoograničenje", "samookljevetan", "samookrivljavanje", "samoomraza", "samoosvešćen", 
  "samootkriće", "samoorganizira", "samooslobođenje", "samooslobođenost", "samoosuda", "samoosvešćenje", "samootpornost", "samootpuštanje", "samoosiguranje", "samooznačavanje", 
  "samoočigled", "samoopleđivanje", "samopašan", "samopašnik", "samopašnost", "samopodsticanje", "samopomaganje", "samopoimanje", "samopojanje", "samopomoć", 
  "samopouzdanje", "samopouzdan", "samopoznanje", "samopodcenjivanje", "samopodizanje", "samopodstaknutost", "samopodsticanje", "samopovlačenje", "samopotvrditi", "samopotvrđivanje", 
  "samopovređivanje", "samopoštovanje", "samopožrtvovanje", "samopredaja", "samoprocena", "samopregoran", "samopregorevanje", "samopregalački", "samopreimućstvo", "samoprelom", 
  "samoprekor", "samoprekoravanje", "samoprepuštanje", "samoprevazilaženje", "samopreispitivanje", "samopreobrazujući", "samoprijekor", "samopriklan", "samoprisutan", "samopriznanje", 
  "samopredan", "samopregorio", "samoprezir", "samoprimirje", "samoprisjećanje", "samopristrano", "samoprocene", "samoprocene", "samoproglašen", "samopritisak", 
  "samoprisegnut", "samoprisjetnost", "samoproglašen", "samoproistekao", "samoprolazni", "samopromotivno", "samoprotivurečan", "samoprovjera", "samoprovjeren", "samoran", 
  "samoranjavanje", "samorastrojen", "samorazaranje", "samorazorna", "samorazoran", "samorazoružanje", "samorazvoj", "samorazotvaran", "samorazvijati", "samorazvojni", 
  "samorazumljiv", "samoregeneracija", "samoregulacija", "samoreklama", "samoreperzentacija", "samodefinisan", "samosabornost", "samosvestan", "samosvest", "samosvijest", 
  "samosvojnost", "samosvojan", "samosvestan", "samosvestin", "samosvestno", "samoosvijetljen", "samosvjetlo", "samosvladavanje", "samosvlast", "samoshvatanje", 
  "samospoznaja", "samossan", "samost", "samostalac", "samostalna", "samostalnost", "samostan", "samostanski", "samosažaljenje", "samosažaljiv", 
  "samosazdan", "samotni", "samotnik", "samotnjački", "samotnjaštvo", "samotno", "samotnost", "samotok", "samotrenutan", "samoubica", 
  "samoubistvo", "samoubilački", "samoubilačko", "samoubojica", "samoubojstvo", "samougušenje", "samounapređenje", "samouništavanje", "samouništenje", "samouništiti", 
  "samoupravan", "samoupravijanje", "samouprava", "samoupravnica", "samoupravni", "samoupravno", "samoupravnost", "samourušen", "samousklađen", "samouslovljen", 
  "samousmeren", "samouspinjanje", "samouspjeće", "samousredsređen", "samousredsređenja", "samousvajanje", "samoutemeljenje", "samoutemeljen", "samoutvrđen", "samoutvrđivanje", 
  "samovaspitanje", "samouvažavanje", "samouveren", "samouverenje", "samouvereno", "samovezivanje", "samoviđen", "samovladanje", "samovlašće", "samovlastan", 
  "samovladan", "samovlasna", "samovlasnost", "samovlast", "samovrsni", "samovrsno", "samovrsnost", "samovrsnu", "samovlasnik", "samovlasništvo", 
  "samovola", "samovoljan", "samovoljno", "samovrednost", "samovredni", "samovrednosti", "samozaborav", "samozaboravan", "samozadovoljavajući", "samozadovoljno", 
  "samozadovoljan", "samozadovoljstvo", "samozadovoljstvo", "samozadržan", "samozamišljeno", "samozamračenje", "samozaokupljen", "samozapaljenje", "samozaokupljenost", "samozasjenjivanje", 
  "samozaštita", "samozačaranje", "samozatajnost", "samozavjerenost", "samozavođenje", "samozavara", "samozavjera", "samozazvan", "samozvanac", "samozvani", 
  "samoživost", "samoživoti", "samoživ", "samoživa", "samuraj", "samurajski", "samuraistvo", "san", "sanacija", "sanacioni", 
  "sanatorij", "sanatorijum", "sanatorijumski", "sandalina", "sandale", "sanduk", "sandučić", "sandučara", "saniran", "sanirati", 
  "sankanje", "sankati", "sankcija", "sankcionisati", "sanke", "sanjak", "sanjanje", "sanjati", "sanjar", "sanjaren", 
  "sanjarenje", "sanjarica", "sanjarija", "sanjariti", "sanjalac", "sanjiv", "sanjivost", "sanjkanje", "sanjkati", "sanjke", 
  "sanjalački", "sanjalačka", "sanjalačko", "sanktgalski", "sansa", "sanskrit", "sanskritolog", "sanskritologija", "sansonijerno", "santimetar", 
  "saobraćajka", "saobraćaj", "saobraćajnica", "saobraćati", "saobraćajni", "saobražaj", "saosećanje", "saosećati", "saopštavati", "saopštenje", 
  "saopštiti", "sapatništvo", "sapatnik", "saplesti", "sapeti", "sapinjati", "sapiranje", "sapirati", "sapientnost", "sapijentan", 
  "sapletati", "saplet", "sapleteno", "sapni", "sapničar", "sapon", "sapun", "sapunast", "sapunar", "sapundžija", 
  "sapuniti", "sapunica", "sapuničiti", "sapunjav", "saputnica", "saputnik", "saradinik", "saradnički", "saradnja", "saradjivati", 
  "sarajlija", "sarajlić", "sarajlika", "sarafan", "saradelfinija", "saradnja", "sarađivati", "sarajevski", "saraj", "saraniti", 
  "sarasin", "sarasvati", "sarati", "sarafiti", "sarači", "sarađenik", "sarađivati", "sarađenost", "saracenski", "saradharmika", 
  "sarakački", "saraklijski", "sarafan", "sarafanjski", "sarafiti", "saraj", "sarajevski", "saraj", "sarakanije", "saramagijski", 
  "saro", "saraj", "saraga", "sarakalija", "sarkastičan", "sarkastičnost", "sarkazam", "sarkom", "sarkomski", "sarkofag", 
  "sarma", "sarmatno", "sarmatski", "sarmati", "sarmica", "saseci", "sasecati", "sasečen", "sasija", "sasijali", 
  "sasijalost", "sasijavanje", "sasijano", "sasinjeno", "sasipati", "sasirati", "sarski", "sastajalište", "sastajati", "sastanak", 
  "sastavak", "sastaviti", "sastavljen", "sastavni", "sastav", "sastavljač", "sastavljati", "sastavnica", "sastojak", "sastojati", 
  "sastojak", "sastojanje", "sastružnik", "sastružac", "sastružak", "sastrug", "sastrugale", "sasunčan", "sasušiti", "sasut", 
  "sasušeni", "sat", "sata", "satan", "satana", "satanski", "satanizam", "satara", "satarenje", "satirač", 
  "satirica", "satiričar", "satirati", "satiričnost", "satiren", "satiriazis", "satirikon", "satiriranje", "satirično", "satiričnost", 
  "satnija", "satnica", "satlić", "satnica", "sator", "satrap", "satrapesha", "satrapija", "satrgnuti", "satrti", 
  "satrvati", "satrven", "saturacija", "saturiran", "saturalija", "saturnijevski", "saturnijski", "saturnali", "saučesništvo", "saučesnik", 
  "saugar", "saugornik", "saugovornik", "saučenik", "saučešće", "saudijski", "saugasnik", "sautjerak", "sautješitelj", "sauzdržanost", 
  "sauzdržan", "sauzakonik", "sauzimanje", "sauzimati", "sauznik", "saučenik", "saučeništvo", "savana", "savanski", "savestan", 
  "savest", "savet", "savetnik", "savetovališni", "savetovanje", "savetodavni", "savetodavac", "savez", "saveznica", "saveznik", 
  "saveznički", "savezništvo", "savijaći", "savijanje", "savijati", "savijen", "savijača", "savijutak", "savit", "savitljivost", 
  "savitljiv", "saviti", "savjet", "savjest", "savladati", "savladan", "savladavanje", "savladivost", "savladiv", "savlast", 
  "savlađivati", "savlekar", "savo", "savoj", "savojski", "savoyski", "savremenik", "savremenost", "savremen", "savršeno", 
  "savršen", "savršenost", "savršenstvo", "savršitelj", "savska", "savski", "savuljar", "savuljaga", "savrstan", "savšenik", 
  "savština", "sazdanje", "sazdati", "sazdan", "sazdavati", "sazdanalje", "sazdanje", "sazdati", "sazeće", "sazidati", 
  "sazidan", "sazimanje", "sazir", "sazirak", "saziralac", "sazirati", "sazivač", "sazivati", "sazivanje", "saziv", 
  "saznajni", "saznalac", "saznalaštvo", "saznanan", "saznanje", "saznati", "saznavalac", "saznavati", "sazov", "sazovitelj", 
  "sazrelost", "sazreo", "sazreti", "sazrijevati", "sazrevanje", "sazrevati", "sazrijevanje", "sazrijevati", "sazvati", "sazvučje", 
  "sazvučan", "sazvučnost", "sazvuk", "sazvati", "sazvežđe", "sazvonce", "sažalan", "sažalijevati", "sažaljenje", "sažalnica", 
  "sažalnost", "sažaljivost", "sažaljiv", "sažalosno", "sažeti", "sažetak", "sažet", "sažetost", "sažimanje", "sažimati", 
  "sažižati", "sceđivati", "scenski", "scedit", "ščepati", "ščeprkanje", "sčekati", "sebičan", "sebično", "sebičnost", 
  "sebičnjak", "sebično", "sebičnost", "sebičluk", "sebičnjak", "sebstvo", "sećanje", "sećati", "sedamdesetogodišnjica", "sedativ", 
  "sedativno", "sedečki", "sedište", "sedlanje", "sedlati", "sedlo", "sednički", "sednica", "sećati", "sećanje", 
  "sećajući", "sećamo", "seda", "sedam", "sedamnaest", "sedamdesetak", "sedamdesetih", "sedanje", "sedativan", "sedativ", 
  "sedati", "sedativnost", "sedamdeset", "sedamdesetoro", "sedamdesetak", "sedamdesetero", "sedamdeseti", "sedamdesetih", "sedamdesetogodišnji", "sedamdesetogodišnjica", 
  "sedamnaest", "sedamnaestero", "sedamnaesti", "sedamnaestogodišnji", "sedativ", "sedativno", "sedef", "sedefasti", "sedefni", "sedeljka", 
  "sedenje", "seden", "sedilac", "sediment", "sedimentacija", "sedimentan", "sedimentiran", "sedište", "sediti", "sediti",
  "sedlanje", "sedlarski", "sedlenje", "sedlar", "sedlarnica", "sedlarstvo", "sedlast", "sedlati", "sedlo", "sedmerac", 
  "sedmerokut", "sedmični", "sedmičnik", "sedmičar", "sedmičarka", "sedmičica", "sedmo", "sedmogodišnjak", "sedmogodišnjica", "sedmogodišnji", 
  "sedmokraki", "sedmorica", "sedmostruk", "sednica", "sednički", "sednuti", "sedokos", "sedokosi", "sedokosa", "segament", 
  "segamnetni", "segregacija", "segregirati", "sehovati", "seizmo", "seizograf", "seizogramski", "seizmički", "seizmograf", "seizmografski", 
  "seizmogram", "seizmološki", "seizmološka", "seizmolog", "sekač", "sekačica", "sekira", "sekiracija", "sekirati", "sekretanja", 
  "sekret", "sekretan", "sekretar", "sekreterica", "sekretirati", "sekonoslje", "sekonos", "sekonoša", "sekta", "sektor", 
  "sektorski", "sekta", "sektaški", "sekularan", "sekularan", "sekundant", "sekundaran", "sekunda", "sekundarac", "sekundarno", 
  "sekundirati", "sekuravatac", "sekuravanje", "sekuravati", "sekurirati", "sekutić", "selcati", "selebritet", "selekcija", "selekcijski", 
  "selektiran", "selektivno", "selektovat", "selem", "selenski", "selenid", "selenski", "seljenje", "seljakinja", "seljački", 
  "seljak", "seljaštvo", "seljanka", "selektiver", "selotejp", "selotejpirati", "seljanin", "seljanka", "selo", "semafor", 
  "semantički", "semantičan", "semantički", "semantika", "semantograf", "semasiološki", "semenište", "semenski", "semenjača", "semenište", 
  "semenkav", "semenica", "semenište", "semet", "seminar", "semiotički", "semtika", "semiotika", "semit", "semitista", 
  "semitistika", "semitologija", "semitstvo", "senator", "senatorstvo", "senatorska", "senatorski", "senatorov", "sendo", "sendvič", 
  "senešal", "senil", "senilnost", "senilan", "senka", "senjor", "senjora", "senke", "senovit", "senzacija", 
  "senzacionalan", "senzacionalizam", "senzibilitet", "senzibilan", "senzibilno", "senzibilizirano", "senzibilnost", "senzualist", "senzualno", "separacija", 
  "separator", "separatizam", "separiran", "sepetembar", "sepsa", "septembra", "septembarski", "septički", "septum", "seraf", 
  "serafički", "serafim", "serbon", "serbokroatisti", "serdarski", "serdar", "serdarevo", "serdarov", "serdžada", "serenada", 
  "serf", "serijski", "serija", "seriozan", "serioznost", "seriozno", "serklirati", "serpentina", "serologija", "seroterapija", 
  "serum", "servilan", "servirati", "servirano", "serviranje", "servis", "servirka", "servilan", "servilijum", "servisiran", 
  "servisiranje", "servisni", "sesija", "sesionalni", "sestrinstvo", "sestrinska", "sestrica", "sestrić", "sestra", "sesvećenik", 
  "setan", "setiti", "setan", "setno", "setnovati", "sevati", "severac", "sevenje", "severnjača", "sever", 
  "severni", "severozapadni", "severoist", "severoma", "severovanje", "severovati", "setva", "sfakidiki", "sfaniotika", "sfera", 
  "sferni", "sfinga", "sfingin", "sfinkter", "sforcato", "sfragistika", "sgrada", "sgradata", "sgoreti", "shabana", 
  "shabanizam", "shakeovski", "shakerizam", "shelijevski", "shema", "shematizam", "shematiziran", "shematski", "shervanika", "sherpa", 
  "shilling", "shintoist", "shitake", "shizoidan", "shizofren", "shizofrenija", "shizma", "shizmatizam", "shoarizam", "shodno", 
  "shofer", "shokolada", "shopenhauer", "shortcut", "shovinizam", "shovinistički", "shteta", "shubarom", "shumaher", "shumar", 
  "shumarski", "shume", "shunka", "shupalj", "shura", "shurak", "shure", "shuteti", "shut", "shutnja", 
  "shutiti", "shutjeti", "shutdown", "shutmancer", "shuto", "shutshelah", "shvajcarski", "shvale", "shvaleri", "shvali", 
  "shvaljen", "shvaler", "shvatanje", "shvatati", "shvaćanje", "shvaćati", "shvati", "shvaćen", "shvaćeni", "si", 
  "sibirac", "sibirski", "sibirjak", "sibilant", "sibilarni", "sibiliacija", "sibilizacija", "sibiliziran", "sibirski", "sibirjački", 
  "sic", "sicve", "sicivica", "sićušan", "sićušnost", "sid", "sidalački", "sidar", "siditi", "sidnuti", 
  "sidro", "siedište", "sief", "sieliti", "sierak", "sieročad", "sierotijna", "sierosivi", "sierota", "sietilac", 
  "sietilo", "sietiti", "sietljiv", "sieva", "siećanje", "siećati", "siedalo", "siedanje", "siedeti", "siedeti", 
  "siedište", "siednica", "sielo", "sieganje", "siegnuti", "sieh", "sieha", "siehati", "siek", "sieka", 
  "siekatica", "siekač", "siekira", "siekirati", "siekretarija", "siekta", "siektor", "siekundarno", "siekutić", "siekvoja", 
  "sielce", "sielendra", "sielendrati", "sieli", "sielica", "sielile", "sielilac", "sielina", "sielište", "sieliti", 
  "sielištance", "sieljanin", "sieljak", "sieljanka", "sielja", "sieljački", "sieljačina", "sieljenje", "sielo", "sielobran", 
  "sielski", "sieluditi", "sieljavati", "sielo", "siemaforizacija", "siemafor", "siemantički", "siemantika", "siemantičar", "siember", 
  "siemce", "siemenar", "siemenik", "siemeni", "siemenjak", "siemenje", "siemenište", "siemenski", "siemerti", "siemester", 
  "siemetričan", "sieminarac", "sieminar", "sieminarski", "siemitolog", "siemja", "siempre", "siemucka", "sien", "siena", 
  "sienam", "siendvič", "sienja", "sienjavati", "sieno", "sienokoš", "sienokošnja", "sienokos", "sienovit", "sieni", 
  "sienovit", "sienovitost", "sienska", "sienski", "sieobe", "sieona", "sieonik", "sieopšti", "sieoski", "siepanje", 
  "sieparacija", "sieparatizam", "sierbez", "sierdar", "sierenada", "sierijal", "sierijalni", "sierijat", "sierijski", "sieroči", 
  "sierotinjski", "sierotinja", "sierotinjski", "sierotonin", "sierozan", "sierpa", "sierpanj", "sierp", "sierpanj", "sierpenti", 
  "sierser", "sierservizi", "sierum", "siervilan", "siervilitet", "siervis", "siervisal", "siervisilica", "siervisiranje", "siervisni",
  "siesar", "siesir", "sieska", "sieslina", "siesne", "siesno", "siester", "siestra", "siestrinskiž", "siesvetinjsko", 
  "sietalan", "sietalan", "sietilac", "sietilo", "sietilni", "sietioce", "sietiti", "sietljiv", "sietljivost", "sietni", 
  "sietniksa", "sietno", "sietnost", "sietnjaci", "sietovanje", "sietoven", "sietovati", "sietvast", "sietven", "sietvenija", 
  "sietveno", "sietveni", "sietvi", "sievač", "sievalo", "sievanje", "sievati", "sievan", "sievene", "sievenjarski", 
  "sievenjak", "siever", "sieverac", "sieveroistočni", "sieveroistok", "sieverno", "sieverni", "sievernoamerički", "sievernjača", "sievernjački", 
  "sieverozapadni", "sieverovati", "sieverski", "sievdah", "sifilis", "sifilitičar", "sifilitički", "sifon", "sifonirati", "sifton", 
  "sigla", "sigma", "sigmoidoskopija", "signatar", "signal", "signalista", "signalizirati", "signalizator", "signalman", "signiranje", 
  "signiran", "signirati", "signifikantno", "signifikantan", "signifikantnost", "siguran", "sigurnjački", "sigurnost", "sigurno", "sigurnosni", 
  "sija", "sijaset", "sijah", "sijalo", "sijalica", "sijamski", "sijanje", "sijati", "sijač", "sijafet", 
  "sijalic", "sijalične", "sijalos", "sijamać", "sijan", "sijanja", "sijanijami", "sijanka", "sijao", "sijaseti", 
  "sijatan", "sijatan", "sijati", "sijač", "sijed", "sijediti", "sijelo", "sijenje", "sijena", "sijer", 
  "sijera", "sijjelo", "sijukati", "sijun", "sik", "sikanje", "sikati", "sikavica", "sikeracija", "sikerica", 
  "sikir", "sikiracija", "sikitati", "sikljati", "siktanje", "siktati", "sila", "silabuski", "silabus", "silama", 
  "silan", "silama", "silana", "silanica", "silart", "silaženje", "silazak", "silaziti", "silazni", "silaznica", 
  "siledzija", "siledžijski", "silen", "silenus", "silenusovski", "silicij", "silicijski", "silikat", "silikon", "silikonski", 
  "silina", "siliti", "silnik", "silno", "silogistički", "silogizam", "silogistički", "silos", "silu", "silovanje", 
  "silovati", "silovit", "silovanje", "silovatelj", "silna", "silovanje", "silovatelj", "silovitost", "silovit", "silovanje", 
  "silovatelj", "simbioza", "simbol", "simboličan", "simbolizirati", "simbolika", "simbolist", "simbolizam", "simetrala", "simetrija", 
  "simetrično", "simetričan", "simfiz", "simfonija", "simfonijski", "simfonist", "simfonista", "simfonijski", "simpati", "simpatičan", 
  "simpatiza", "simpatizirati", "simpatija", "simpatičnost", "simpatičan", "simpatizer", "simplificirati", "simplicitet", "simplifikacija", "simpliciran", 
  "simulacija", "simulant", "simulirati", "simultan", "simunski", "sinak", "sinaksa", "sinatra", "sinapse", "sinatre", 
  "sinatra", "sinbad", "sinče", "sindarhija", "sindikalista", "sindikat", "sindikalizam", "sindikatski", "sindiklani", "sindikalistički", 
  "sindikalni", "sindrom", "sindžir", "sinema", "sinematički", "sinematogerafija", "sinestezija", "sinergijski", "sinergija", "sinergički", 
  "sinestetičan", "sinestetički", "sinestezija", "singl", "singlton", "singularitet", "singularan", "singularnost", "sinji", "sinjela", 
  "sinji", "sinjedrionist", "sinjedrion", "sinjig", "sinjora", "sinjoreti", "sinjoriti", "sinjorini", "sinkopa", "sinkopirati", 
  "sinkretizam", "sinkro", "sinkroni", "sinkopirani", "sinkopiran", "sinkroni", "sinkronizacija", "sinkroniziran", "sinkronizm", "sinoć", 
  "sinoćni", "sinoćni", "sinoćnji", "sinod", "sinodal", "sinodalni", "sinodijalan", "sinodijski", "sinodski", "sinonim", 
  "sinoniman", "sinonimika", "sinonimijan", "sinonimnost", "sinoptičar", "sinoptika", "sinoptički", "sinovčev", "sinovac", "sinovljevo", 
  "sinovljev", "sintagma", "sintagmatski", "sintaksa", "sintaksni", "sintaksički", "sintetički", "sinteza", "sintetizirati", "sintetizator", 
  "sintetizon", "sintetizuju", "sintetizovati", "sintetski", "sinteza", "sintezom", "sinteza", "sintetizirati", "sinteznost", "sintezno", 
  "sinusi", "sinus", "sinusitis", "sinusni", "sipa", "sipača", "sipanje", "sipati", "sipavica", "siplji", 
  "sipljiv", "sipljivac", "sipljivost", "sirće", "sirena", "sirenski", "siresijasti", "sirevina", "sirila", "sirilnik", 
  "sirilo", "sirinje", "sirinjava", "siriti", "sirijus", "sirina", "siriške", "siriaz", "sirijum", "sirijanac", 
  "sirijski", "siročad", "siročadi", "siročadski", "siromah", "siromahan", "siromahova", "siromaštvo", "siromašni", "siromašno", 
  "siromaštan", "sirotan", "sirotinjski", "sirotinja", "sirotiška", "sirotište", "sirovost", "sirov", "sirovo", "sirovost", 
  "sisaljka", "sisaljka", "sisanje", "sisara", "sisati", "sister", "sisak", "sisarski", "sise", "sisaljke", 
  "sisaljki", "sisanski", "sisatost", "sisavac", "sisavci", "sisanje", "sisati", "sisača", "sistem", "sistemni", 
  "sisteman", "sistemantski", "sisematično", "sistematika", "sistematizacija", "sistematizacija", "sistematizirati", "sistematizovati", "sistematika", "sistematičnost", 
  "sistematski", "sistemnost", "sistemni", "sistemski", "sistem", "sitit", "sititi", "sitničav", "sitno", "sitničari",
  "sitnina", "sitost", "situacija", "siva", "sivkast", "sivoća", "skakač", "skakavac", "skakanje", "skakati", 
  "skala", "skalamerija", "skalpel", "skamenjiti", "skandal", "skandinav", "skanjivati", "skakutanje", "skapavati", "skaredno", 
  "skaska", "skat", "skatološki", "skaut", "skazaljka", "skečiranje", "skeč", "skela", "skelet", "skepticizam", 
  "skica", "skiciranje", "skidanje", "skidati", "skijanje", "skijati", "skijaški", "skitnica", "skitati", "sklapanje", 
  "sklapati", "sklanjati", "sklizak", "sklizište", "sklon", "sklonost", "sklopiti", "sklopljen", "sklupčati", "skoba", 
  "skočiti", "skokovi", "skori", "skorašnji", "skoro", "skot", "skotnost", "skov", "skovan", "skovati", 
  "skovrčati", "skraja", "skrajnuti", "skraćenica", "skraćeno", "skraćivati", "skrama", "skratiti", "skrenuti", "skrhati", 
  "skriven", "skrivati", "skriveno", "skromnost", "skroman", "skroz", "skrpiti", "skrušiti", "skrutiti", "skučen", 
  "skučenost", "skulptor", "skulptura", "skup", "skupiti", "skupljač", "skupljati", "skupni", "skupocen", "skupština", 
  "skut", "skutriti", "skuvati", "skvašen", "sladak", "sladoled", "slagalica", "slagati", "slama", "slanje", 
  "slast", "slastica", "slatko", "slava", "slavina", "slavljenik", "slaviti", "slavuj", "slede", "sledbenik", 
  "sledeći", "slediti", "slegati", "sleđen", "slepa", "slepac", "slepoća", "sleva", "slevati", "sležbina", 
  "slezan", "slezina", "slika", "slikar", "slikarski", "slikarstvo", "slikati", "slikovit", "slikovnica", "slina", 
  "slinav", "sliv", "slivati", "slivnik", "slog", "sloga", "slojevi", "slom", "slomiti", "slon", 
  "slonovski", "slonovača", "sloboda", "slobodan", "slobodni", "slog", "sloga", "slom", "sloga", "slovo", 
  "složen", "sluga", "službeni", "službenik", "služenje", "služiti", "slučaj", "slučajan", "slučajno", "smeđ", 
  "smeđ", "smehotvroni", "smejačica", "smejuljenje", "smelost", "smenjivati", "smeo", "smenjivanje", "smenjivost", "smer", 
  "smesa", "smesta", "smeštaj", "smeštati", "smesti", "smešiti", "smetati", "smetlišta", "smetnja", "smežurati", 
  "smicalica", "smicanja", "smignuti", "smiriti", "smiraj", "smiren", "smirenost", "smisliti", "smisao", "smišljen", 
  "smokva", "smokvica", "smola", "smolast", "smoriti", "smrtan", "smrtnost", "smrt", "smrtonosno", "smrznuti", 
  "smuljati", "smučiti", "smušen", "smutnja", "snaći", "snaja", "snajan", "snabdeti", "snabdevanje", "snabdevač", 
  "snabdjevač", "snabdijevanje", "snaga", "snažan", "snatriti", "sneg", "snega", "snevarati", "snezina", "snimak", 
  "snimatelj", "snimiti", "snimka", "sniženica", "sniženje", "snižen", "sniziti", "snobizam", "snop", "snopić", 
  "snovanje", "snovati", "snovitelj", "snovitost", "snošaj", "snubljenje", "snubiti", "sobarica", "sobni", "sočan", 
  "sočivo", "sočna", "sočno", "sočnost", "socijalizam", "socijalan", "sociologija", "soda", "sodomija", "sofizam", 
  "softver", "soha", "sojenica", "sokak", "sokolac", "sokolarstvo", "sokolarstvo", "sokol", "sokolovo", "sokovnik", 
  "solarni", "solarijum", "solidan", "solidarnost", "solidno", "soliti", "solista", "solisaonica", "solisati", "soliter", 
  "solfeđo", "solistički", "soliti", "soliter", "soljenje", "soljenka", "sombrero", "somet", "sonda", "sonata", 
  "sonet", "sonik", "sonografski", "sonornost", "soperništvo", "sopran", "sopranist", "sopranistica", "sopranistkinja", "sopranistica", 
  "sopstveni", "sopstvo", "soptati", "sorabija", "sorbcijon", "sorbonac", "sorbonski", "sorcijerna", "sorta", "sortiment", 
  "sortirati", "sortirani", "sorti", "sosijer", "sosijerovski", "sospitator", "sosovi", "sotona", "sotiljno", "sova", 
  "sovan", "sovhoz", "sovin", "sovina", "sovir", "sovjetija", "sovjetizacija", "sovjetski", "sozercanje", "sozercateljan", 
  "sočinitelj", "sočiniti", "sočinjavati", "sočitati", "sočiti", "sočivo", "sočivast", "sočni", "sočnina", "sočnost", 
  "spa", "spacirati", "spacirano", "spacijalan", "spacijaliziran", "spanać", "spanač", "spandžijski", "sparan", "sparivanje", 
  "spariti", "sparan", "spariti", "sparivati", "sparološki", "spartanac", "spartanski", "spasa", "spasavanje", "spasava", 
  "spasavanjem", "spasavati", "spasenije", "spasenje", "spasenjski", "spasibo", "spasitelj", "spasiteljica", "spasiti", "spasonosan", 
  "spasti", "spavaći", "spavaonica", "spavanje", "spavati", "specijalan", "specifičnost", "specifičan", "specijalisti", "specijalist", 
  "specijalistički", "specifikacija", "specifikovan", "specirati", "specijalitet", "specijum", "specijalistica", "specijalka", "specfični", "specljalnost", 
  "spektakl", "spektakularan", "spektar", "spektator", "spektralan", "spektrografija", "spektroskop", "spekulacija", "spekulant", "spekulirati", 
  "spelunka", "spev", "spetljati", "spiralnost", "specifičan", "spirala", "spiralni", "spiritizam", "spiritist", "spiritus", 
  "spisak", "spisateljski", "spisateljestvo", "spit", "splačina", "splahnuti", "spletke", "splav", "splavar", "spletkati", 
  "splin", "spljeskati", "spljesnuti", "spljošten", "spodobe", "spodoban", "spodobnijik", "spogodbe", "spogodben", "spoj", 
  "spojiti", "spokoj", "spokojan", "spokojstvo", "spol", "spolni", "spoljašnji", "spoljni", "spomen", "spomenik", 
  "spomenuti", "spona", "sponzor", "sporan", "sporazum", "spori", "sporost", "sportski", "sposoba", "sposobljenost", 
  "sposoban", "spotaći", "spratan", "spravljati", "sprava", "spraviti", "sprega", "spregnuti", "sprečiti", "sprva", 
  "spremač", "spremati", "spremiti", "spretni", "spretnost", "sprijeda", "sprijeda", "spropast", "sprovod", "sprovesti", 
  "sprskati", "sprudni", "sprudovi", "sprud", "sprut", "sprva", "spuditi", "spuknuti", "spustiti", "srački", 
  "sračunati", "sračunatost", "sradnji", "sraknuti", "sraman", "sramežljiv", "sramota", "sramotiti", "sramno", "sramna", 
  "srpanje", "srpski", "srpovi", "srpski", "srce", "srceparajući", "srčan", "srčanost", "srdačan", "srdit"
];

// Dodaj nove reči u rečnik
async function addToMegaDictionary() {
  try {
    // Pročitaj postojeće reči
    const data = fs.readFileSync(dictionaryPath, 'utf8');
    let words = JSON.parse(data);
    
    console.log(`Trenutni broj reči: ${words.length}`);
    
    // Dodaj nove reči
    const uniqueWords = new Set([...words, ...additionalWords]);
    const updatedWords = Array.from(uniqueWords);
    
    // Sačuvaj ažurirani rečnik
    fs.writeFileSync(dictionaryPath, JSON.stringify(updatedWords, null, 2), 'utf8');
    
    console.log(`Novi broj reči: ${updatedWords.length}`);
    console.log(`Dodato ${updatedWords.length - words.length} novih reči.`);
  } catch (error) {
    console.error(`Greška pri dodavanju reči: ${error}`);
  }
}

// Pozovi funkciju
addToMegaDictionary();