import fs from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

// Get directory path
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const dictionaryPath = path.resolve(__dirname, '../server/data/serbian-dictionary-mega.json');

// Nove srpske reči za dodati
const additionalWords = [
  // P
  "pabirdžija", "pabirčar", "pacati", "pacificirati", "pacifikator", "pacifizam", "pacifistički", "pacifist", "packa", 
  "pacov", "padalište", "padavica", "padavine", "padež", "padina", "pagar", "paganski", "paginacija", "paginjacija", 
  "pagoda", "paganski", "pagan", "pagubno", "pah", "pahati", "pahulja", "pahati", "pahuljičast", "pahuljica", 
  "pajalica", "pajac", "pajati", "pajeti", "pajdaš", "pajdašiti", "pajtaš", "pajser", "paka", "paketići", 
  "paket", "paklena", "pakleni", "paklenica", "paklo", "pakovati", "pakost", "pakovati", "pakovanje", "palac", 
  "palača", "palačinka", "paladij", "palanka", "palamar", "palast", "palata", "palce", "pali", "palica", 
  "palih", "palisad", "palisada", "palisandrov", "paliti", "paljba", "paljenje", "paljeti", "paljeva", "paljevina", 
  "paljevi", "paljka", "paljkati", "paljuga", "palog", "paloma", "palost", "paluba", "paludina", "palčić",
  "pamet", "pametan", "pamflet", "pamfletist", "pampur", "pametara", "pametnica", "pametni", "pametnog", "pametovanja", 
  "pamtiti", "pampur", "pamučni", "pamuk", "panaceja", "panada", "panafrički", "panagia", "panahida", "panatela", 
  "panađur", "pancer", "pandant", "pandekti", "panel", "panfitizam", "panfletista", "panforte", "panica", "paničarka", 
  "paničarenje", "panikaš", "paništvo", "paničan", "paničar", "panjevi", "pant", "panta", "pantaloni", "panter", 
  "panteon", "pantljika", "pantomim", "pantomima", "pantomimičar", "panurati", "panjaga", "panjat", "panjevi", "papa", 
  "papar", "papagaj", "papagajstvo", "papaja", "papaluk", "papandopulo", "papati", "papazjanija", "papci", "papiga", 
  "papiga", "papirnati", "papir", "papirnat", "papirologija", "papirni", "papirčina", "papiruski", "paplan", "paplonski", 
  "papovka", "paprat", "papratna", "paprika", "paprikaš", "papučar", "papučarka", "papudžika", "papudžijski", "papuča", 
  "papučica", "paprika", "paradajz", "paradioma", "paraf", "parafiranje", "parafin", "parafinski", "paragraf", "paragvajski", 
  "parajlija", "paraknjiževnost", "paralaksa", "paralela", "paralelitet", "paralelizam", "paralelno", "paraliziran", "paralogizam", "paramantati", 
  "paramatematika", "parameću", "parametar", "paramita", "paramilitaran", "paranoja", "paranojičan", "paranormalan", "paraolimpijski", "parapet", 
  "parapeti", "paraplegičar", "parapsiholog", "parcela", "parcelacija", "parcijalan", "parčad", "parčati", "pardane", "paredak", 
  "parentela", "parentera", "parenica", "parenično", "parenično", "pariška", "paripski", "paritetski", "paritet", "park", 
  "parket", "parkirati", "parni", "parnica", "parodija", "parodijski", "parodirati", "parohija", "parohijski", "paroksizam", 
  "parolići", "parola", "partisan", "partizan", "partizanstvo", "partner", "partija", "participating", "participcije", "particip", 
  "participacija", "participirati", "partijac", "partijski", "partikula", "partikularizam", "partijska", "partitiv", "partizan", "partizanski", 
  "partitura", "parvenjstvo", "parvenu", "parzen", "pasakalja", "pasaulji", "pasati", "pasaža", "pasaži", "pasat", 
  "pasent", "pasija", "pasijans", "pasivan", "pasivnost", "pasivno", "pasja", "pasji", "paskvila", "pasmine", 
  "pasoca", "pasoglavac", "pasosh", "pasoški", "pasoš", "pasoški", "pastele", "pastelno", "pastelić", "pasterizacija", 
  "pasterizirati", "pasteta", "pastikan", "pastir", "pastirski", "pastorala", "pastuh", "pastušiti", "pasvord", "pašaluk", 
  "pašalik", "paša", "pašanac", "pašipolje", "paškog", "paški", "paško", "pašteta", "pašta", "pašte", 
  "patafizika", "pataki", "patakubo", "patalački", "pataljak", "patarena", "patčenat", "pateinstvo", "patelin", "patenat", 
  "patentiran", "patentiranje", "patentirati", "patentni", "paterio", "patetična", "patetični", "patetika", "patetizacija", "patibulum",
  "patika", "patina", "patinasti", "patinirati", "patisar", "patisona", "patka", "patljika", "patlidžani", "patnja", 
  "patogen", "patogeneza", "patogeni", "patogenom", "patognost", "patološki", "patologija", "patologkinja", "patološki", "patologija", 
  "patrik", "patriot", "patriotizam", "patriotski", "patriša", "patrijarh", "patrijarhalno", "patrijarhalni", "patrijarski", "patrola", 
  "patrolarenje", "patronažni", "patron", "patrona", "patronat", "patikbir", "patur", "paturati", "pauci", "paučina", 
  "paučinast", "paučje", "pauka", "paukovo", "paun", "paunica", "paunovke", "paunovo", "pauper", "pauperizacija", 
  "pauperizirati", "paus", "pauza", "paučinasto", "paučinasta", "pavane", "pavijan", "paviljon", "paviljončić", "pavitina", 
  "pavle", "pavlimir", "pavlinski", "pavlović", "pavor", "pavši", "pazarište", "pazariti", "pazarka", "pazarsko", 
  "pazar", "pažev", "pažen", "pažikati", "pažljiv", "pažnja", "pažljiv", "pažnja", "pačart", "pačaura", 
  "pačić", "pačji", "pačuli", "pačvork", "pašče", "peć", "peći", "pedagogija", "pedagog", "pedagoški", 
  "pedala", "pedalj", "pedaliran", "pedant", "pedanter", "pedanterija", "pedantnost", "pedesetak", "peder", "pederast", 
  "pederski", "pedigriran", "pedigre", "pedijatar", "pediatar", "pedijatrija", "pedira", "pedikirka", "pedofil", "pedofilija", 
  "pedologija", "pegasti", "pegaz", "pegic", "pegla", "peglač", "peglan", "peglati", "pehati", "pehar", 
  "pehlivaniti", "peitet", "pejsaž", "pejzažist", "pejzažista", "pektinom", "pektura", "pektoral", "pekmezara", "pekar", 
  "pekarski", "pekines", "pekmez", "pekoni", "pektin", "pelcovati", "pelcer", "pelerina", "pelikan", "pelikanski", 
  "pelir", "pelivan", "pelud", "peludi", "peludnjaka", "peludnica", "peludice", "pelvisi", "pemza", "penal", 
  "penali", "penalizacije", "penalti", "pencijoni", "pendel", "pendirati", "pendrek", "pendžer", "penetracija", "penetrirati", 
  "penica", "penicilinski", "penicin", "penjač", "penjati", "penkalo", "penis", "penkala", "penkalo", "pentagon", 
  "pentagrami", "pentan", "pentatonika", "pentekostalni", "penzija", "penzioner", "penzionerski", "penzionirati", "penzionisan", "penzionisati", 
  "peoni", "pepeljara", "pepeljast", "pepeljuga", "pepeo", "pepito", "peplum", "pepper", "pepsi", "peptid", 
  "perač", "perača", "peraja", "peraja", "perak", "perast", "peraški", "perač", "perači", "percepicirati", 
  "percipiraj", "percipiranje", "percipirajte", "percepcija", "perceptivnost", "perda", "perdah", "perdašiti", "perdomil", "perece", 
  "pereka", "pereka", "perenijalan", "perestrojka", "perfekcija", "perfekt", "perforator", "perfumerija", "pergament", "pergola", 
  "perhiberni", "periferijski", "periferija", "periferijski", "perifernost", "perika", "periko", "perimetar", "perina", "perinski", 
  "period", "perioda", "periodni", "periodika", "periodički", "periodično", "peripatetički", "peripetija", "periton", "peritonealni", 
  "perjanic", "perjanik", "perjanica", "perjaničiti", "perje", "perla", "permanentan", "permutacija", "peron", "persifliran", 
  "persirati", "persirati", "personalan", "personifikacija", "persijski", "perstilaz", "pertinencija", "peršun", "pertle", "perućica", 
  "peruanski", "perunike", "peruta", "perutanje", "peruti", "pervaziti", "perverznjaci", "perverzenjak", "perverzija", "perverzan", 
  "pervertirati", "perzist", "perzijski", "pesak", "peskovit", "pesma", "pesnički", "pesnica", "pesnik", "pesmati", 
  "pesničiti", "pesmice", "pesmičice", "pesimist", "pesimizam", "peso", "pesticid", "pešačiti", "pešadija", "pešak", 
  "peščani", "pešće", "pešice", "peškir", "peta", "petak", "petao", "peteljka", "petero", "peterokatnica", 
  "peterosoban", "peterovalentni", "peticija", "petina", "petica", "petkati", "petlja", "petljanje", "petljati", "petni", 
  "petokolon", "petogodišnjica", "petokraka", "petori", "petorica", "petoročlan", "petospratan", "petrarkist", "petrel", "petrifikacija", 
  "petrificirano", "petroglijf", "petrogradski", "petrograf", "petrol", "petrolejka", "petrovača", "petrozavodački", "petrović", "petrovdanski", 
  "petrovački", "petu", "petula", "petunija", "peć", "pećina", "pećinski", "peša", "pešačenje", "pevač", 
  "pevačica", "pevač", "pevanje", "pevati", "pešice", "pešadinac", "pešadijski", "pešak", "peškir", "pigment", 
  "pijanista", "pikado", "pikantno", "pikati", "pika", "piknik", "pilići", "pilotirati", "pinceta", "pinjata", 
  "piramida", "pisac", "pisaći", "pismo", "pistacio", "pištolj", "pitalica", "pitanje", "pitka", "pivara", 
  "pivnica", "pivski", "pivo", "pižama", "plafon", "plaćanje", "planina", "planinarski", "planirati", "planski", 
  "plastičan", "plastika", "platforma", "platiti", "platno", "plato", "plavac", "plavičast", "plaviti", "plavuša", 
  "ples", "plesač", "plesni", "plesan", "pletenje", "plin", "plinska", "plivač", "plivati", "plivaški", 
  "plodnost", "ploča", "pločica", "pločnik", "plućni", "pluća", "pluta", "plutati", "pljeskavica", "pljuvanje", 
  "pobeda", "pobeđivati", "poboljšati", "pobornik", "pobuđivati", "pobuna", "pocerati", "počasni", "početi", "početak", 
  "počev", "počinje", "podaci", "podatak", "podizati", "podjela", "podloga", "podmititi", "podnevlje", "podnijeti", 
  "podnožje", "podnositi", "podocnjak", "pododbor", "podravnati", "podrum", "podseća", "podseća", "podsetnik", "podstanar", 
  "podudarati", "poduhvat", "poduzeti", "podvig", "poezija", "poet", "poetika", "pogled", "pogibija", "pogledati", 
  "pogodak", "pogonski", "pogreška", "pogrešan", "pogrom", "pogubiti", "pohađati", "pohitati", "pohlepan", "pohlepa", 
  "pohrana", "pohvala", "pohvaliti", "pojas", "pojačalo", "pojačati", "pojačavati", "pojaviti", "pojedini", "pojedinac", 
  "pojesti", "pojilo", "pojiti", "pojmiti", "pojmovno", "pokazatelj", "pokazati", "pokazivati", "poklanjati", "poklisar", 
  "pokloniti", "poklopac", "pokop", "pokoriti", "pokositi", "pokraj", "pokrenuti", "pokret", "pokretač", "pokrivač", 
  "pokućar", "pokućstvo", "pokus", "pokušati", "polako", "polagati", "polarni", "polaznik", "polazak", "polemika", 
  "polemičar", "policija", "policajac", "polimen", "poliglota", "poligon", "polimeri", "polirana", "politički", "politika", 
  "poljana", "poljski", "poljubac", "poljuljati", "polako", "polagan", "poleći", "polehnut", "polufinale", "poluga", 
  "polukrug", "polumesec", "polunaga", "polusestra", "polustepen", "polutka", "polovni", "polovina", "pomama", "pomaknuti", 
  "pomalo", "pomanjkati", "pomesti", "pometenost", "pomfrit", "pomicati", "pomoć", "pomoćni", "pomogao", "pomognuti", 
  "pomozite", "pompa", "pompezno", "pomnožiti", "pomoliti", "pomoći", "pomognem", "pomognu", "pomor", "pomorstvo", 
  "ponavljati", "ponekad", "poneki", "ponestati", "poneti", "ponešto", "poniziti", "poniženje", "ponižen", "poniranje", 
  "ponirući", "ponositi", "ponosan", "ponuda", "ponuditi", "ponuknuti", "popara", "popakovati", "popaliti", "popara", 
  "popečitelj", "popeti", "popijemo", "popis", "popisivati", "popiti", "poplave", "poplašiti", "poplun", "popodne", 
  "popodnevni", "popović", "popodnevlje", "popona", "poprimiti", "poprsje", "popraviti", "popravak", "popravljen", "popričati", 
  "poprilično", "poprimljen", "poprimiti", "poprskan", "popržiti", "popuniti", "popunjivati", "popuštati", "popustiti", "pora", 
  "poradi", "poraz", "porazan", "poravnati", "poraz", "poraziti", "porazgovarati", "porazbijati", "porazbolevati", "porazumeti", 
  "porculan", "porećati", "poredak", "poreklom", "poremećaj", "porest", "porez", "poricati", "porinut", "pornografija", 
  "porobiti", "porođaj", "porota", "portabl", "portal", "portir", "portret", "porub", "porubljivati", "poruka", 
  "poručati", "poručiti", "porušiti", "posada", "posaditi", "posao", "posavina", "poseći", "poseban", "posejan", 
  "poseljačiti", "posesivan", "poseta", "posetiti", "posetilac", "posiliti", "posilni", "posinak", "posipati", "posisati", 
  "posiveo", "posjediti", "poskočiti", "poskok", "poslanik", "poslastica", "poslastičar", "posledica", "poslednji", "poslije", 
  "posle", "poslenik", "poslijepodne", "poslenik", "posluga", "posluživati", "poslušno", "poslovati", "poslovan", "poslovica", 
  "poslovnost", "posmatrati", "posmrtnica", "posmrtni", "posmuda", "posniti", "posni", "posno", "posnik", "posol", 
  "pospanost", "pospano", "posprdno", "posrbiti", "posred", "posredan", "posrednik", "posrnuti", "post", "postaja", 
  "postajati", "postavljen", "postaviti", "postdiplomski", "poster", "posteljina", "postelja", "posteljina", "posteriorno", "postfiks", 
  "posthladnoratni", "posthladnoratnom", "posthladnoratnu", "posthodno", "posthumno", "postice", "postimpresionistički", "postinfarktni", "postiti", "postizanje", 
  "postizati", "postmoderna", "postmodernistic", "postmodernistički", "postmodernizam", "postojanje", "postojbina", "postojeći", "postojano", "postotak", 
  "postpenal", "postradalima", "postroj", "postrojka", "postrojiti", "postskriptum", "posttrauma", "posttraumatski", "posttraumatsko", "postupak", 
  "postupkom", "postupan", "postupci", "postupiti", "postupno", "postulant", "posuda", "posuđe", "posudba", "posuditi", 
  "posuđe", "posumnjati", "posuti", "posvaditi", "posvađati", "posve", "posvećen", "posvetiti", "posvetilo", "posvećen", 
  "posvjetovnjačiti", "posvuda", "potajice", "potaknuti", "potamaniti", "potapšati", "potapkati", "potapkavati", "potapkivati", "potapljiv", 
  "potapljanje", "potapljati", "potapljač", "potapljiv", "potapljujući", "potpala", "potpaliti", "potpalublje", "potpaluba", "potparol", 
  "potpetica", "potpetice", "potpirivati", "potpis", "potpisati", "potpisnik", "potpisan", "potpisati", "potpuno", "potpora", 
  "potprašiti", "potprašionica", "potres", "potraga", "potražiti", "potraživati", "potraživač", "potrepština", "potreba", "potreban", 
  "potrebito", "potruditi", "potrošač", "potrošnja", "potući", "potucanje", "potuljeno", "poturaliti", "potvrda", "potvrditi", 
  "potvrdan", "pouzdanost", "pouzdan", "povampiren", "povampiriti", "povelja", "poverenje", "poverovati", "poverilac", "poveriti", 
  "povijest", "povijest", "povijesni", "povijen", "povijesnica", "povijesno", "povjeren", "povjerenje", "povjeriti", "povjerenik", 
  "povjerljivost", "povjerenica", "povjest", "povjestičar", "povjestičarka", "povlaka", "povlašćivati", "povlastiti", "povlastica", "povlašteni", 
  "povlačiti", "povoda", "povreda", "povrediv", "povrediti", "povredljiv", "povredljivo", "povremeno", "povremeni", "povrt", 
  "površan", "površina", "površinski", "povući", "povukao", "povezan", "povezanost", "povez", "povezivati", "poveznica", 
  "povici", "povišeni", "povišica", "povodom", "povodac", "povoljan", "povratan", "povratiti", "povratak", "povratni", 
  "povrediti", "povredljivo", "povredljiv", "povremeno", "povrtnjak", "povrtlar", "povuka", "povukovati", "pošteden", "poštovati", 
  "pozadina", "pozan", "pozajmiti", "pozamašan", "pozadi", "pozajmljujem", "pozajmljivati", "poznato", "poznanik", "poznanje", 
  "poznati", "poznavalac", "poznavati", "pozni", "poznica", "pozno", "poziđe", "poziv", "pozivanje", "pozivnica", 
  "pozitivno", "pozitivan", "pozitivno", "pozivati", "pozlata", "pozlatiti", "pozlaćen", "poznavalački", "pozobati", "pozorište", 
  "pozornica", "pozornik", "pozornost", "pozorišni", "pozorno", "pozoban", "pozobanost", "požar", "požarevački", "požeški", 
  "poželjeti", "poželjno", "poželjan", "požgati", "požnjeti", "požuda", "požudno", "požudan", "požuri", "požuriti", 
  "požurnica", "požuteo", "požuteti", "praktičan", "praktični", "pračovek", "prađed", "prafaktor", "pragerski", "pragonitelj", 
  "pragovjeran", "praguslav", "pragmatično", "pragmatičan", "prakljača", "praksa", "praktično", "praktikant", "praktičnost", "pramac", 
  "pramati", "pramajka", "pramen", "praoblik", "praonica", "praocem", "praporac", "prapovijest", "prapovjesni", "praotac", 
  "prasak", "praskati", "praskozorje", "praskav", "prasnuti", "prašina", "prašinast", "prastarogrčki", "prasnuti", "pratećim", 
  "pratilac", "pratiti", "pratnja", "pravac", "pravda", "pravdanje", "pravdati", "pravdan", "pravdanski", "pravdaški", 
  "pravedan", "pravednički", "pravednik", "pravica", "pravičan", "praviti", "pravilo", "pravilno", "pravilnik", "pravilnost", 
  "praviti", "pravljen", "pravljenje", "pravo", "pravobranilac", "pravolinijski", "pravopis", "pravosuđe", "pravoslavni", "pravougaonik", 
  "pravovaljan", "pravovjernost", "pravovjerski", "prazan", "praznički", "prazničan", "praznik", "praznina", "prazniti", "praznoglavac", 
  "praznovjerje", "praznovjeran", "praznosloviti", "praznovanje", "praznoslavlje", "praznoslovi", "pražnjenje", "pražnjeti", "pražniti", "pređašnji", 
  "pređenje", "pređica", "prebahat", "prebačaj", "prebaciti", "prebaviti", "prebeliti", "prebijati", "prebirati", "prebirati", 
  "prebogat", "prebog", "prebojiti", "preboleti", "prebolijevati", "preboriti", "prebrati", "prebrijati", "prebrisati", "prebrinuti", 
  "prebroditi", "prebrojiti", "prebuditi", "prebujan", "preburan", "preceniti", "precijenjeno", "precizno", "precizirati", "precrtati", 
  "prečaga", "prečesto", "prečinjati", "prečica", "prečistiti", "prečišćivati", "prečka", "prečuti", "pred", "predaja", 
  "predak", "predanje", "predan", "predano", "predasati", "predati", "predator", "predavač", "predavanje", "predavati", 
  "predgovor", "predigra", "predivno", "predivan", "predizborni", "prednačiti", "pred", "predmet", "prednačiti", "prednost", 
  "prednjačiti", "prednjica", "predočiti", "predosećaj", "predosetiti", "predočiti", "predrag", "predrasuda", "predstava", "predstaviti", 
  "predstavka", "predstavnik", "predstavnistva", "predsednik", "predsjedavati", "predsjednik", "predsoblje", "predstojati", "predstojnik", "predugo", 
  "preduhitriti", "preduzeti", "preduzimati", "predveče", "predvideti", "predziđe", "prefiks", "prefinjeno", "prefiks", "preferenca", 
  "preferirati", "preferirani", "prefiks", "prefinjeno", "prefrontal", "pregalac", "pregaoc", "preganjati", "pregib", "pregibi", 
  "pregled", "pregledati", "pregledaš", "pregledavati", "pregledno", "preglednost", "pregledni", "pregolema", "pregoreo", "pregraditi", 
  "pregraniziran", "pregrda", "pregristati", "pregriz", "pregrmeti", "pregršt", "pregrubi", "pregrupa", "pregrupacija", "pregrupirati", 
  "prehititi", "prehladiti", "prehlada", "prehladni", "prehladit", "prehrana", "prehrambeno", "preispitati", "preispitivati", "preistorijski", 
  "prejak", "prejedati", "prekaljeni", "prekaljen", "prekaljenje", "prekid", "prekinut", "prekjuče", "prekjučerašnji", "preklati", 
  "preklinjati", "preklon", "preklopiti", "preklapati", "prekobrojan", "prekomerno", "prekomponirati", "prekonoć", "prekontrola", "prekontrolisati", 
  "prekookeanski", "prekoračati", "prekoračenje", "prekoračiti", "prekoriti", "prekorni", "prekosutra", "prekrajati", "prekrajanje", "prekratiti", 
  "prekrasan", "prekrcati", "prekretnica", "prekriven", "prekrižiti", "prekrojiti", "prekršaj", "prekršiti", "preksinoć", "preksinočnji", 
  "prekuvati", "prelaz", "prelazak", "prelaziti", "prelemiti", "preležati", "prelep", "prelevati", "preliven", "prelistavati", 
  "prelistiti", "prelivati", "prelom", "prelomni", "preludij", "preludiranje", "premalo", "premašiti", "premeštati", "premetatija", 
  "premetati", "premetačina", "premetaljka", "premetanje", "premetenost", "premestiti", "premija", "premijera", "premilostiv", "premirna", 
  "premisa", "premlad", "premlada", "premladost", "premošćivati", "premostiti", "premotati", "premršav", "premudri", "premudrost", 
  "premudar", "premučen", "premučiti", "premz", "prenaglasiti", "prenapet", "prenatrpan", "preneseno", "prenesti", "preneražen", 
  "prenerazio", "preneraženost", "prenet", "preneti", "prenoćiti", "prenos", "prenositi", "prenosni", "prenosnik", "prenosiv", 
  "preobiman", "preobilno", "preobličiti", "preoblikovanje", "preoblikovati", "preobrate", "preobražaj", "preobrazba", "preobraženje", "preobući", 
  "preobuti", "preobuvka", "preocean", "preodgoj", "preodgovoran", "preodrediti", "preokupirati", "preokrenuti", "preokret", "preokretati", 
  "preokupiran", "preokupirani", "preopširan", "preopteretiti", "preoranženost", "preostajati", "preostalo", "preostati", "preoteti", "preotimati", 
  "prepad", "prepasti", "prepečenica", "prepelica", "prepešačiti", "prepina", "prepiranje", "prepirati", "prepirka", "prepisati", 
  "prepisivanje", "prepisivati", "prepišati", "preplakati", "preplanuo", "preplašiti", "preplatiti", "preplesti", "preplitati", "preplov", 
  "preploviti", "prepluta", "prepokrivati", "prepoloviti", "prepoznati", "prepoznatljiv", "preprati", "prepredati", "prepreden", "prepredenost", 
  "prepredenjak", "prepričati", "prepričavanje", "preprodavati", "preprogramirati", "preprostor", "prepucavanje", "prepustiti", "prepuštati", "prepun", 
  "prepuniti", "prepunjenost", "prerada", "prerađen", "prerađivanje", "prerađivati", "prerasti", "prerastao", "prerijskog", "preračunavati", 
  "prerano", "prerazmernost", "preraznolikost", "prerušiti", "prerušavanje", "presa", "presadi", "presaditi", "presadnica", "presamititi", 
  "presavijanje", "presavijati", "presavijen", "presaviti", "presavijen", "presedeti", "presek", "presekao", "presekati", "preseknuti", 
  "preseliti", "preseljenje", "presenetn", "presenetiti", "presenetnost", "presenetno", "presenetna", "presetica", "presijavati", "presijecati", 
  "presipati", "presjecati", "presjecen", "presjedati", "presjesti", "preskakanje", "preskakati", "preskakivanje", "preskakivati", "preskočiti", 
  "preskok", "preskakalo", "preskrbljivanje", "preskribirati", "preskribiran", "preskupo", "preslaba", "preslatko", "preslava", "preslagivanje", 
  "preslagivati", "preslik", "preslikati", "preslikavati", "presložiti", "presložno", "presmeo", "presoliti", "presnimak", "presnimati", 
  "presnimavati", "presnimiti", "presor", "prespavati", "prespoj", "prespreman", "prestajati", "prestali", "prestanak", "prestankom", 
  "prestati", "prestrašiti", "prestrog", "prestrukturiran", "prestupiti", "presuda", "presudan", "presuditi", "presušiti", "presvijetao", 
  "presvisnuti", "presvlačiti", "presvlaka", "presvratiti", "presvući", "presvukao", "prešutati", "prešutjeti", "pretakati", "pretapati", 
  "pretapala", "pretapanje", "pretegnuti", "pretečak", "pretendirati", "pretenciozno", "pretencioznost", "pretenzija", "preterano", "preterati", 
  "preterivanje", "pretendent", "preternuti", "preteriti", "pretezan", "pretezati", "prethistorija", "preti", "pretilost", "pretinac", 
  "pretisak", "pretiskano", "pretiti", "pretjeran", "pretjerano", "pretjerati", "pretjeranost", "pretkapitalizam", "pretkomora", "pretkraj", 
  "pretopao", "pretopiti", "pretopla", "pretovar", "pretovarati", "pretovariti", "pretovaruje", "pretpostavljam", "pretpostavljeni", "pretpostavka", 
  "pretpovijesni", "pretpretprošli", "pretprošli", "pretprostor", "pretproljeće", "pretprošle", "pretprošlost", "pretprošlogodišnji", "pretraga", "pretraživati", 
  "pretraživač", "pretraživanje", "pretrgnut", "pretrgnuti", "pretrpavanje", "pretrpavati", "pretrpan", "pretrpati", "pretrpenost", "pretrpjeti", 
  "pretura", "preturiti", "pretužno", "pretvara", "pretvaralište", "pretvaranje", "pretvarati", "pretvoriti", "pretvoren", "pretvrda", 
  "preučen", "preudaja", "preudati", "preumoran", "preumorno", "preumereno", "preupitan", "preuzeti", "preuzevši", "preuzimati", 
  "preuzimanje", "prevaga", "prevarno", "prevarljivost", "prevaran", "prevarant", "prevariti", "prevazići", "prevedeni", "prevejan", 
  "prevencija", "preventiva", "preveo", "prevesti", "prevelik", "prevesti", "prevesti", "prevezati", "previd", "prevideti", 
  "previdjeti", "previše", "previti", "previjanje", "previrati", "prevladati", "prevlaka", "prevoz", "prevoziti", "prevoznik", 
  "prevoženje", "prevrata", "prevratan", "prevratiti", "prevratnik", "prevratnički", "prevratniku", "prevrćati", "prevrnuti", "prevrnuo", 
  "prevrtljiv", "prevrućo", "prevući", "prevukao", "prezadužena", "prezaduženi", "prezaduženje", "prezadužiti", "prezasposleno", "prezasićenost", 
  "prezasićen", "prezauzetost", "prezauzet", "prezbiterium", "prezdan", "prezdrav", "prezeba", "prezeljit", "prezentan", "prezent", 
  "prezentacija", "prezentirati", "prezimena", "prezimiti", "prezimljavanje", "prezimovati", "prezirno", "prezirati", "prezira", "preziranjima", 
  "preziratelj", "prezir", "prezirna", "preživeli", "preživeo", "preživeti", "preživjeti", "preživljavanje", "preznamenovati", "prezren", 
  "prezrenec", "prezriv", "prezrivanje", "prezrivati", "prženje", "pržina", "pržionica", "pržioničar", "pržiti", "pržun", 
  "pribadača", "pribaviti", "pribavljanje", "pribežište", "pribijanje", "pribira", "pribjeći", "pribjegavanje", "pribjeglica", "pribiti", 
  "pribjegla", "pribjeći", "pribježište", "pribježni", "pribojavati", "pribor", "pričalica", "pričaonica", "pričati", "pričest", 
  "pričestiti", "pričin", "pričinjavati", "pričinjati", "pričinjeno", "pričinjenje", "pričuvan", "pričuvni", "pričvrstiti", "pričvršćen"
];

// Dodaj nove reči u rečnik
async function addToMegaDictionary() {
  try {
    // Pročitaj postojeće reči
    const data = fs.readFileSync(dictionaryPath, 'utf8');
    let words = JSON.parse(data);
    
    console.log(`Trenutni broj reči: ${words.length}`);
    
    // Dodaj nove reči
    const uniqueWords = new Set([...words, ...additionalWords]);
    const updatedWords = Array.from(uniqueWords);
    
    // Sačuvaj ažurirani rečnik
    fs.writeFileSync(dictionaryPath, JSON.stringify(updatedWords, null, 2), 'utf8');
    
    console.log(`Novi broj reči: ${updatedWords.length}`);
    console.log(`Dodato ${updatedWords.length - words.length} novih reči.`);
  } catch (error) {
    console.error(`Greška pri dodavanju reči: ${error}`);
  }
}

// Pozovi funkciju
addToMegaDictionary();